[package]
name = "ap-cv"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
image.workspace = true
imageproc.workspace = true
async-channel.workspace = true

criterion.workspace = true
wgpu = "27.0.1"
bytemuck = { version = "1.24.0", features = ["derive"] }
pollster = "0.4.0"

[[bench]]
name = "match"
harness = false