[package]
name = "auto-play-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "auto_play_py"
crate-type = ["rlib", "cdylib"]


[dependencies]
auto-play.workspace = true
pyo3 = { version = "0.27.2", features = ["extension-module", "abi3-py38"] }
